version: '3'

services:
  web:
    build: . 
    image: mini-ionic
    env_file: .env
    command: bash -c "npm install --rebuild && /usr/local/bin/ionic serve --no-open"
    volumes:
      - .:/ionic-project
    working_dir: /ionic-project/myApp
    ports:
      - 8100:8100

  debug:
    build: . 
    image: ionic
    privileged: true
    network_mode: host
    env_file: .env
    command: ["/usr/local/bin/ionic", "cordova", "run", "android", "--livereload", "--consolelogs"]
    volumes:
      - .:/ionic-project
      - /dev/bus/usb:/dev/bus/usb
    working_dir: /ionic-project/myApp
    ports:
      - 8100:8100
      - 35729:35729
